### ISSUE TITLE
House calculations and planet longitudes not matching with Swiss Ephemeris

### ISSUE THREAD

**Issue by amitabh-srivastav** [ryuphi/astrology-api#15]
The effort put in by you is appreciable. However, when I checked with Swiss Ephemeris the results are at variance. To test it, I used following data: date =11th May 2000, place longitude 78.00, Latitude 13.00, Time 5:30AM Time zone +5:30 i.e. UT=0.00  , House system=Placidus
So the test url was :
 https://dev-astrology-api.herokuapp.com/horoscope?time=2000-05-11T05:30:00%2B05:30&latitude=13.000&longitude=78.000
The Ascendant result was "{"asc":{"position":{"degrees":13,"minutes":17,"seconds":25,"longitude":43.29034759846253},"sign":2}"
While using test page of astro.com,  https://www.astro.com/swisseph/swetest.htm  with following "Option =  -b11.05.2000 -p -house78.00,13.00,P -ut0:00" the result obtained are as follows:
/ulb/swetest -b11.5.2002 -n1 -s1 -fPLBRS -pp -eswe -b11.05.2000 -p -house78.00,13.00,P -ut0:00 
date (dmy) 11.5.2000 greg.   0:00:00 UT		version 2.10.01a
UT:  2451675.500000000     delta t: 63.931325 sec
TT:  2451675.500739946
geo. Long 78.000000, Lat 13.000000, alt 0.000000
Epsilon (t/m)     23°26'16.8419   23°26'21.2387
Nutation          -0° 0'16.2303   -0° 0' 4.3967
Houses system P (Placidus) for long=  78° 0' 0.0000, lat=  13° 0' 0.0000
house  1          43°17'21.1025  394° 5'19.7268
house  2          72°11' 5.8018  344°39' 3.5695
house  3          98°14'41.3484  330°45'22.6552
house  4         124°44'25.4895  351°24'55.2438
house  5         154°26'51.7827  393°54'22.7902
house  6         188°15'42.1466  419°56'24.2202

Another software (using Swiss Ephemeris) gives exactly same House positions as above. But the result given by your implementation has a difference of about 4" of arc.

Please check and revert back.

**Comment by ryuphi** [comment]
Thank you for reporting the issue ❤️ 

The difference of this implementation with respect to others, is that it was intended to use Universal Coordinated Time (UTC). For this we used the methods recommended by swisseph in their documentation https://www.astro.com/swisseph/swephprg.htm#_Toc71121194. Unfortunately, as you noticed, this was causing a difference in the internal calculations of the swisseph library. 

To be more clear, the swesstest tool is calculating different UT depending on the method used. If to that tool you instead of the option to use universal time (-ut0:00) you enter the option to use UTC (-utc0:00:00:00) the positions delivered by the api were the same. The issue is that swisseph calculates a UT of 0:00:00.253 for that time in UTC.

```
/ulb/swetest -b11.05.2000 -n1 -s1 -fPTJLLlBbRGgIi -p -eswe -house78.000,13.000,P -utc00:00:00 
date (dmy) 11.5.2000 greg.   0:00:00.253 UT version 2.10.01a
UT: 2451675.500002924 delta t: 63.931325 sec
TT: 2451675.500742870
geo. long 78.000000, lat 13.000000, alt 0.000000
Epsilon (t/m) 23°26'16.8419 23°26'21.2387
Nutation -0° 0'16.2303 -0° 0' 4.3967
Houses system P (Placidus) for long= 78° 0' 0.0000, lat= 13° 0' 0.0000
house 1 11.05.2000 0:00:00 UT 2451675.50000 43°17'25.2514 43.2903476
[...]
```

That small difference in milliseconds causes a difference in the latitude delivered by the library and in the calculations based on it.

I have my doubts if it is really an issue, but I will upload a correction so that the calculation of the Julian day does not go through the function that uses UTC. This will perhaps provide a standardization with what is already in other software and avoid confusion. But as I say, more than an issue, it is a matter of how it was intended to be used. 

Now personally, I don't think that the 4" difference in the arc will generate differences in the generation of the natal chart unless for some aspect that uses very narrow orbs and is between slower planets, asteroids or other points where the aspects would tend to be more accurate.

**Comment by amitabh-srivastav** [comment]
Thanks Dear for attending to the bug and standardization of the calculation process.
Actually, to the user's of KP astrology , this 4" difference matters a lot, as it changes the Sub-lords and Sub-sub lords (Rulership of 249th division and 2193rd division of the zodiac) .
Thanks again for this wonderful work.
